name: flatpak
command: ["flatpak"]
args: ["install", "-y"]
post-install:
  [
    "flatpak",
    "--remote-add",
    "--if-not-exists",
    "flathub",
    "https://flathub.org/repo/flathub.flatpakrepo",
  ]
packages:
  - md.obsidian.Obsidian
